language: php
sudo: false
branches:
  except:
    - v0.5
    - v0.6
    - v0.6-PHP_5.2
    - documentation
before_install:
  - docker run -d --rm -p 127.0.0.1:6379:6379 redis:${REDIS_VERSION:=3}
before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
script:
  - travis_retry vendor/bin/phpunit -c phpunit.xml.travisci
matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: REDIS_VERSION=4
    - php: 7.4
      env: REDIS_VERSION=5
    - php: 7.4
      env: REDIS_VERSION=6
    - php: nightly
  allow_failures:
   - php: nightly
